site_name: Bryllite.NET Docs
site_url: https://trieton-works.github.io/docs/
site_author: jade
site_description: Bryllite.NET API document repository
# Repository
repo_name: trieton-works/docs
repo_url: https://github.com/trieton-works/docs/

extra_css:
  - assets/css/extra.css

copyright: Bryllite.NET. All Rights Reserved.
extra:
  generator: false

# Configuration
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.indexes
    # - navigation.prune
    # - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - glightbox:
      effect: zoom
      width: 100%
      height: auto
      auto_caption: true
      caption_position: bottom

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - tables
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.keys
#  - pymdownx.magiclink:
#      repo_url_shorthand: true
#      user: squidfunk
#      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      base_path: ['docs']
      auto_append:
        - inc/glossary.md
  - pymdownx.tilde
   
nav:
  - Home:
    - API References: api/index.md
    - Cosmic P2P: p2p/index.md
